version: '3'

services:
  web:
    image: nginx:stable
    container_name: dnd_web
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
